// Auto-generated by scripts/generate-auth.js — DO NOT edit manually
// Contains only hashes. Plaintext credentials are in .env (gitignored).
window.AUTH_CONFIG = {
  userHash: "d52219e01118208f6d59f4ad051787ec02d0dc028b57e746b74f5506bb3ad1ac",
  passHash: "fa04842dd6d3bd201d99cc93ef0296d6931dd102530917413f7d3893ad7c4d3c",
  salt: "39ccef19a17c655ee73811125dfa5e0faf1dd32203c7a45c0539907d5c833036"
};
