#!/usr/bin/env node
/**
 * scripts/generate-auth.js
 *
 * Reads AUTH_USER, AUTH_PASSWORD, AUTH_SALT from .env
 * Computes SHA-256(user) and PBKDF2(password, salt, 310000) hashes
 * Writes window.AUTH_CONFIG to auth-config.js at repo root
 *
 * Usage: node scripts/generate-auth.js
 * Runtime: Node.js >= 18 (uses built-in crypto — no npm install needed)
 */

const { createHash, pbkdf2 } = require('crypto');
const fs = require('fs');
const path = require('path');

// ── Load .env ────────────────────────────────────────────────────────────────

const envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
  console.error('Error: .env not found. Copy .env.example to .env and fill in values.');
  process.exit(1);
}

const envVars = {};
fs.readFileSync(envPath, 'utf8')
  .split('\n')
  .forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    envVars[key] = value;
  });

const { AUTH_USER, AUTH_PASSWORD, AUTH_SALT } = envVars;

if (!AUTH_USER || !AUTH_PASSWORD || !AUTH_SALT) {
  console.error('Error: .env must contain AUTH_USER, AUTH_PASSWORD, and AUTH_SALT.');
  console.error('Generate a salt with: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"');
  process.exit(1);
}

// ── Compute hashes ───────────────────────────────────────────────────────────

// SHA-256 of username
const userHash = createHash('sha256').update(AUTH_USER, 'utf8').digest('hex');

// PBKDF2 of password: SHA-256, 310,000 iterations, 32-byte key
// IMPORTANT: AUTH_SALT is a hex string — must decode to raw bytes before use.
// Both Node and browser must treat salt as the same raw bytes, not ASCII chars.
const saltBuffer = Buffer.from(AUTH_SALT, 'hex');
pbkdf2(AUTH_PASSWORD, saltBuffer, 310000, 32, 'sha256', (err, derivedKey) => {
  if (err) {
    console.error('Error computing PBKDF2:', err.message);
    process.exit(1);
  }

  const passHash = derivedKey.toString('hex');

  // ── Write auth-config.js ───────────────────────────────────────────────────

  const outputPath = path.join(__dirname, '..', 'auth-config.js');
  const content = `// Auto-generated by scripts/generate-auth.js — DO NOT edit manually
// Contains only hashes. Plaintext credentials are in .env (gitignored).
window.AUTH_CONFIG = {
  userHash: "${userHash}",
  passHash: "${passHash}",
  salt: "${AUTH_SALT}"
};
`;

  fs.writeFileSync(outputPath, content, 'utf8');
  console.log('✓ auth-config.js written successfully');
  console.log(`  User hash:  ${userHash.slice(0, 16)}...`);
  console.log(`  Pass hash:  ${passHash.slice(0, 16)}...`);
  console.log(`  Salt:       ${AUTH_SALT.slice(0, 16)}...`);
});
